version: "3.9"
services:
  greet_server:
    build: ./greet_server
    volumes:
      - ./greet_server:/greet_backend
    ports:
      - '50051:50051'
  medium_envoy:
    build: ./envoy
    ports:
      - '8000:8000'
      # - '9901:9901'